---
Parameters:

  AvailabilityZone:
    Type: String
    Default: us-east-1a
  AmazonLinux2AMI:
    Type: String
    Default: ami-0b5eea76982371e91

Resources:
  DockerComposeInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      ImageId: !Ref AmazonLinux2AMI
      InstanceType: t2.2xlarge	
      UserData: 
        Fn::Base64:
          | 
          #!/bin/bash
          yum update -y

          # Mount Drive
          mkdir /data
          mkfs -t xfs /dev/xvdh
          mount /dev/xvdh /data

          # Install Docker Compose
          curl -L https://github.com/docker/compose/releases/download/1.29.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

          # Install Docker
          amazon-linux-extras install docker -y
          service docker start
          systemctl enable docker
          usermod -a -G docker ec2-user
          chmod 666 /var/run/docker.sock

          # Move docker data to the new drive
          sudo mkdir -p /data/docker
          sudo mv /var/lib/docker /data/docker
          sudo ln -s /data/docker /var/lib/docker
          sudo systemctl restart docker

          # Install git in your EC2 instance
          yum install git -y

          cd ~
          git clone https://github.com/idinsight/danswer.git
          cd danswer
          git checkout mb-experimenting
          /usr/local/bin/docker-compose -f ~/danswer/deployment/docker_compose/docker-compose.dev.yml -p danswer-stack up -d --build --force-recreate

      SecurityGroups:
        - !Ref SSHSecurityGroup
        - !Ref HTTPSecurityGroup

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        ToPort: 22
        IpProtocol: tcp

  HTTPSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable standard web access
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          FromPort: 80
          ToPort: 80
          IpProtocol: tcp

  ExternalVolume:
    Type: AWS::EC2::Volume
    Properties: 
      AvailabilityZone: !Ref AvailabilityZone
      Size: 150
      VolumeType: gp2

  MountPoint:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !Ref DockerComposeInstance
      VolumeId: !Ref ExternalVolume
      Device: /dev/xvdh

  ElasticIp:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref DockerComposeInstance