name: Deploy to staging EC2

on:
  pull_request:
    branches:
      - staging
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.STAGING_EC2_SSH_PRIVATE_KEY }}

      - name: SSH and Deploy to EC2
        run: ssh -o StrictHostKeyChecking=no ec2-user@3.108.64.73 << 'EOF'
              docker ps -q | xargs -r docker kill        
              docker system prune -af
              cd /home/ec2-user/danswer
              git fetch origin staging
              git reset --hard FETCH_HEAD
              docker-compose -f /home/ec2-user/danswer/deployment/docker_compose/docker-compose.prod.yml up -d --force-recreate
              EOF
