name: Send Slack Metrics

on:
  schedule:
    - cron: '*/5 * * * *'
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$PROD_SSH_KEY" > ~/.ssh/hubgpt_prod.key
          chmod 600 ~/.ssh/hubgpt_prod.key
          cat >>~/.ssh/config <<END
          Host prod
            HostName $PROD_EC2_HOST_IP
            User $PROD_EC2_USER
            IdentityFile ~/.ssh/hubgpt_prod.key
            StrictHostKeyChecking no
          END
        env:
          PROD_EC2_USER: ${{ secrets.PROD_EC2_USER }}
          PROD_SSH_KEY: ${{ secrets.PROD_SSH_KEY }}
          PROD_EC2_HOST_IP: ${{ secrets.PROD_EC2_HOST_IP }}

      - name: Trigger metric dispatch
        run: |
          ssh prod << 'EOF'
          cd danswer
          docker exec danswer-stack-background-1 sh -c\
           'export METRICS_CHANNEL_ID=$METRICS_CHANNEL_ID; \
           export SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN; python\
            /app/scripts/send_slack_report/send_slack_report.py'
          EOF

        env:
          METRICS_CHANNEL_ID: ${{ secrets.METRICS_CHANNEL_ID }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}